### ISSUE TITLE
Algorithm broken again

### ISSUE THREAD

**Issue by paddy919** [ffluegel/zippyshare#10]
Quick and dirty fix.

`line 32:        filename="$( cat "${infofile}" | grep "/d/" | cut -d'/' -f6 | cut -d'"' -f1 | grep -o "[^ ]\+\(\+[^ ]\+\)*" )"`
`line 55:        dlbutton="$( grep -oE 'var a = [0-9]+' ${infofile} | grep -oE '[0-9]+' | sed 's/a()/1/g' | sed 's/b()/2/g' | sed 's/c()/3/g' | sed 's/d/4/g' )"`
`line 61:        dlbutton="$( grep 'getElementById..dlbutton...href' "${infofile}" | grep -oE '\([0-9].*\)' | sed 's/a()/1/g' | sed 's/b()/2/g' | sed 's/c()/3/g' | sed 's/d/4/g' )"`

Sry, I can't be bothered creating a PR right now.

Greetz

**Comment by ffluegel** [comment]
Thanks for reporting, it should be fixed now.
