### ISSUE TITLE
Something changed?

### ISSUE THREAD

**Issue by IamMrZ** [ffluegel/zippyshare#11]
Script failing to find the filename this morning (failing with " could not download file from" message). 

Links work from browser.

**Comment by ffluegel** [comment]
Thanks for reporting, should be fixed now

**Comment by IamMrZ** [comment]
Fails with "could not get zippyshare url algorithm"

**Comment by ffluegel** [comment]
Sorry, try again please

**Comment by IamMrZ** [comment]
Works. Thanks!
